include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.g.dart"
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error


